"""Storage protocols -- focused interfaces for the pluggable storage layer."""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Protocol, runtime_checkable

from ..types import (
    ChunkEmbedding,
    ConversationStats,
    EngineStateSnapshot,
    Fact,
    FactLink,
    LinkedFact,
    QuoteResult,
    StoredSegment,
    StoredSummary,
    TagStats,
    TagSummary,
)


@runtime_checkable
class SegmentStore(Protocol):
    """Segments, summaries, tag summaries, tags, and aliases."""

    def store_segment(self, segment: StoredSegment) -> str: ...
    def get_segment(self, ref: str, *, conversation_id: str | None = None) -> StoredSegment | None: ...
    def get_summary(self, ref: str, *, conversation_id: str | None = None) -> StoredSummary | None: ...
    def get_summaries_by_tags(
        self, tags: list[str], min_overlap: int = 1, limit: int = 10,
        before: datetime | None = None, after: datetime | None = None,
        conversation_id: str | None = None,
    ) -> list[StoredSummary]: ...
    def search(self, query: str, tags: list[str] | None = None, limit: int = 5, conversation_id: str | None = None) -> list[StoredSummary]: ...
    def get_all_tags(self, conversation_id: str | None = None) -> list[TagStats]: ...
    def get_conversation_stats(self) -> list[ConversationStats]: ...
    def get_tag_aliases(self) -> dict[str, str]: ...
    def set_tag_alias(self, alias: str, canonical: str) -> None: ...
    def delete_segment(self, ref: str) -> bool: ...
    def cleanup(self, max_age: timedelta | None = None, max_total_tokens: int | None = None) -> int: ...
    def save_tag_summary(self, tag_summary: TagSummary) -> None: ...
    def get_tag_summary(self, tag: str) -> TagSummary | None: ...
    def get_all_tag_summaries(self, *, conversation_id: str | None = None) -> list[TagSummary]: ...
    def get_segments_by_tags(self, tags: list[str], min_overlap: int = 1, limit: int = 20, conversation_id: str | None = None) -> list[StoredSegment]: ...
    def get_orphan_tag_snippets(self, limit: int = 1000) -> list[dict]: ...


@runtime_checkable
class FactStore(Protocol):
    """Fact CRUD, querying, and supersession."""

    def store_facts(self, facts: list[Fact]) -> int: ...
    def query_facts(
        self, *, subject: str | None = None, verb: str | None = None,
        verbs: list[str] | None = None, object_contains: str | None = None,
        status: str | None = None, fact_type: str | None = None,
        tags: list[str] | None = None, limit: int = 50,
        conversation_id: str | None = None,
    ) -> list[Fact]: ...
    def get_unique_fact_verbs(self, *, conversation_id: str | None = None) -> list[str]: ...
    def get_facts_by_segment(self, segment_ref: str) -> list[Fact]: ...
    def search_facts(self, query: str, limit: int = 10, conversation_id: str | None = None) -> list[Fact]: ...
    def set_fact_superseded(self, old_fact_id: str, new_fact_id: str) -> None: ...
    def update_fact_fields(self, fact_id: str, verb: str, object: str, status: str, what: str) -> None: ...
    def get_fact_count_by_tags(self, *, conversation_id: str | None = None) -> dict[str, int]: ...
    def get_superseded_facts(self, fact_ids: list[str]) -> list[dict]: ...


@runtime_checkable
class FactLinkStore(Protocol):
    """Fact link CRUD and traversal."""

    def store_fact_links(self, links: list[FactLink]) -> int: ...
    def get_fact_links(self, fact_id: str, direction: str = "both") -> list[FactLink]: ...
    def get_linked_facts(self, fact_ids: list[str], depth: int = 1) -> list[LinkedFact]: ...
    def delete_fact_links(self, fact_id: str) -> int: ...


@runtime_checkable
class StateStore(Protocol):
    """Engine state persistence."""

    def save_engine_state(self, state: EngineStateSnapshot) -> None: ...
    def load_engine_state(self, conversation_id: str) -> EngineStateSnapshot | None: ...
    def load_latest_engine_state(self) -> EngineStateSnapshot | None: ...
    def list_engine_state_fingerprints(self) -> dict[str, str]: ...


@runtime_checkable
class SearchStore(Protocol):
    """Full-text search and embedding storage."""

    def search_full_text(self, query: str, limit: int = 5, conversation_id: str | None = None) -> list[QuoteResult]: ...
    def store_chunk_embeddings(self, segment_ref: str, chunks: list[ChunkEmbedding]) -> None: ...
    def get_all_chunk_embeddings(self) -> list[ChunkEmbedding]: ...
    def store_tool_output(self, ref: str, conversation_id: str, tool_name: str, command: str, turn: int, content: str, original_bytes: int) -> None: ...
    def search_tool_outputs(self, query: str, limit: int = 5, conversation_id: str | None = None) -> list: ...
