"""Regression: operation_id generated by _run_compact must be a
Postgres-castable UUID string, not a truncated 12-char hex.

Observed in production: ``state.py:2078`` generated
``uuid.uuid4().hex[:12]`` (e.g. ``'116a7e245bbb'``). Postgres's
``compaction_operation.operation_id`` column is ``UUID`` type and
rejects that with ``InvalidTextRepresentation: invalid input syntax
for type uuid``. ``enter_compaction`` swallowed the exception, letting
the compaction run on the legacy in-memory path — but without a DB row
the takeover pipeline had nothing to recover from across restarts, and
the heartbeat sidecar then spam-failed on the same cast.
"""
from __future__ import annotations

import re
import uuid as _uuid
from pathlib import Path

import pytest


_UUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
)


def test_run_compact_generates_full_uuid(tmp_path: Path):
    """Drive _run_compact on the normal (non-takeover) path, capture the
    operation_id it finalizes via _active_compaction_op, and assert it
    matches a canonical UUID string — not a 12-char hex prefix.
    """
    from unittest.mock import MagicMock, patch
    from tests.test_handle_prepare_payload import _make_proxy_state

    state = _make_proxy_state(tmp_path)
    captured: dict[str, object] = {}

    def _capture(*args, **kwargs):
        captured["op_at_pipeline"] = state._active_compaction_op
        return None

    with patch.object(state.engine, "compact_if_needed", side_effect=_capture), \
         patch.object(state, "enter_compaction", new_callable=MagicMock), \
         patch.object(
             state.engine._store, "read_progress_snapshot",
             return_value=MagicMock(active_compaction=None),
         ):
        state._run_compact(
            history=[], signal=None, turn=0, turn_id="",
            preexisting_operation_id=None,
        )

    op = captured.get("op_at_pipeline")
    assert op is not None, (
        "_active_compaction_op must be set before compact_if_needed runs"
    )
    assert _UUID_RE.match(op), (
        f"operation_id must be a canonical UUID string (Postgres UUID column "
        f"rejects truncated hex); got {op!r}"
    )
    # And round-tripping through uuid.UUID() must succeed.
    _uuid.UUID(op)  # raises ValueError if not a valid UUID


def test_run_compact_takeover_respects_preexisting_id(tmp_path: Path):
    """When preexisting_operation_id is supplied (takeover path), it
    must pass through verbatim — not be re-truncated.
    """
    from unittest.mock import MagicMock, patch
    from tests.test_handle_prepare_payload import _make_proxy_state

    state = _make_proxy_state(tmp_path)
    takeover_uuid = str(_uuid.uuid4())
    captured: dict[str, object] = {}

    def _capture(*args, **kwargs):
        captured["op"] = state._active_compaction_op
        return None

    with patch.object(state.engine, "compact_if_needed", side_effect=_capture), \
         patch.object(state, "enter_compaction", new_callable=MagicMock), \
         patch.object(
             state.engine._store, "read_progress_snapshot",
             return_value=MagicMock(active_compaction=None),
         ):
        state._run_compact(
            history=[], signal=None, turn=0, turn_id="",
            preexisting_operation_id=takeover_uuid,
        )

    assert captured.get("op") == takeover_uuid, (
        f"Takeover path must use supplied operation_id verbatim; "
        f"got {captured.get('op')!r}"
    )
