"""Community-engagement candidate pipeline.

Read-only. Selects and proves candidates; posts nothing and schedules
nothing. Scheduling and delivery live outside the engine.
"""

from .allowlist import (
    POST_CHANNEL_IDS,
    SOURCE_CHANNEL_IDS,
    REHEARSAL_CONFIG,
    rehearsal_allowlist,
)
from .history import (
    ENGAGEMENT_HISTORY_DDL,
    apply_engagement_history_schema,
    DayAlreadyClaimed,
    InMemoryPostHistory,
    PostgresPostHistory,
    PostRecord,
    check_repetition,
    fingerprint_distance,
    topic_fingerprint,
)
from .schedule import (
    SCHEDULE_ENABLED_BY_DEFAULT,
    ScheduleWindow,
    may_run_now,
    plan_day,
    preview_schedule,
)
from .broader import (
    BROADER_GENERATOR_GUIDANCE,
    CLAIM_CHECKER_SYSTEM_PROMPT,
    BroaderGeneratorNotConfigured,
    BroaderQuestion,
    generate_broader_question,
    validate_broader_question,
)
from .continuation import (
    CONTINUATION_HOOK_KINDS,
    HOOK_DETECTOR_SYSTEM_PROMPT,
    ContinuationHook,
    HookDetectorNotConfigured,
    find_continuation_hook,
    qualify_candidates,
)
from .live_source import (
    BLOCKING_REASONS,
    LIVE_AUTHOR_MISMATCH,
    LIVE_CHANNEL_MISMATCH,
    LIVE_DELETED,
    LIVE_EDITED,
    LIVE_FORBIDDEN,
    LIVE_RATE_LIMITED,
    LIVE_UNREACHABLE,
    LiveVerification,
    select_live_verified,
    verify_source_live,
)
from .poster import (
    POSTING_ENABLED,
    PostRefused,
    PostResult,
    already_posted_today,
    pending_claims,
    post_question,
)
from .runner import RunResult, run_once
from .candidates import Candidate, Rejection, collect_candidates
from .compose import (
    CONTINUATION_GUIDANCE,
    TONE_CONSTRAINTS,
    Draft,
    DraftComposerNotConfigured,
    compose_continuation_draft,
    compose_draft,
    strip_speaker_prefix,
)
from .channels import ChannelAllowlist, load_channel_allowlist
from .fidelity import (
    ADVERSARIAL_FIDELITY_FIXTURES,
    FIDELITY_JUDGE_SYSTEM_PROMPT,
    FidelityFixture,
    FidelityGateNotConfigured,
    FidelityVerdict,
    run_fidelity_gate,
)
from .report import DryRunReport
from .select import (
    REASON_BROADER_POOL_EMPTY,
    REASON_BROADER_POOL_NOT_CONFIGURED,
    REASON_BROADER_QUESTIONS_RECENT,
    REASON_NO_CANDIDATES,
    SelectionOutcome,
    apply_fidelity_outcome,
    rank_candidates,
    select_question,
)
from .timing import ThreadState, assess_thread, timed_followup_eligibility
from .sources import load_message_sources
from .verify import MessageSourceRecord, verify_candidates

__all__ = [
    "ADVERSARIAL_FIDELITY_FIXTURES",
    "FIDELITY_JUDGE_SYSTEM_PROMPT",
    "POST_CHANNEL_IDS",
    "REHEARSAL_CONFIG",
    "SOURCE_CHANNEL_IDS",
    "ENGAGEMENT_HISTORY_DDL",
    "apply_engagement_history_schema",
    "DayAlreadyClaimed",
    "InMemoryPostHistory",
    "PostgresPostHistory",
    "PostRecord",
    "check_repetition",
    "fingerprint_distance",
    "topic_fingerprint",
    "SCHEDULE_ENABLED_BY_DEFAULT",
    "ScheduleWindow",
    "may_run_now",
    "plan_day",
    "preview_schedule",
    "BROADER_GENERATOR_GUIDANCE",
    "CLAIM_CHECKER_SYSTEM_PROMPT",
    "BroaderGeneratorNotConfigured",
    "BroaderQuestion",
    "generate_broader_question",
    "validate_broader_question",
    "CONTINUATION_HOOK_KINDS",
    "HOOK_DETECTOR_SYSTEM_PROMPT",
    "ContinuationHook",
    "HookDetectorNotConfigured",
    "find_continuation_hook",
    "qualify_candidates",
    "BLOCKING_REASONS",
    "LIVE_AUTHOR_MISMATCH",
    "LIVE_CHANNEL_MISMATCH",
    "LIVE_DELETED",
    "LIVE_EDITED",
    "LIVE_FORBIDDEN",
    "LIVE_RATE_LIMITED",
    "LIVE_UNREACHABLE",
    "LiveVerification",
    "select_live_verified",
    "verify_source_live",
    "POSTING_ENABLED",
    "PostRefused",
    "PostResult",
    "already_posted_today",
    "pending_claims",
    "post_question",
    "RunResult",
    "run_once",
    "Candidate",
    "rehearsal_allowlist",
    "strip_speaker_prefix",
    "compose_continuation_draft",
    "compose_draft",
    "CONTINUATION_GUIDANCE",
    "TONE_CONSTRAINTS",
    "DraftComposerNotConfigured",
    "Draft",
    "ChannelAllowlist",
    "DryRunReport",
    "FidelityFixture",
    "FidelityGateNotConfigured",
    "FidelityVerdict",
    "MessageSourceRecord",
    "load_message_sources",
    "Rejection",
    "REASON_BROADER_POOL_EMPTY",
    "REASON_BROADER_POOL_NOT_CONFIGURED",
    "REASON_BROADER_QUESTIONS_RECENT",
    "REASON_NO_CANDIDATES",
    "SelectionOutcome",
    "ThreadState",
    "apply_fidelity_outcome",
    "assess_thread",
    "collect_candidates",
    "load_channel_allowlist",
    "rank_candidates",
    "run_fidelity_gate",
    "select_question",
    "timed_followup_eligibility",
    "verify_candidates",
]
