"""Agentic preset — balanced defaults for autonomous agent conversations."""

from __future__ import annotations

from .base import Preset, register_preset


AGENTIC_CONFIG: dict = {
    "version": "0.2",
    "storage_root": ".virtualcontext",
    "context_window": 120_000,
    "token_counter": "estimate",
    "paging": {
        "enabled": True,
        "auto_promote": True,
        "auto_evict": True,
        "max_tool_loops": 10,
    },
    "tag_generator": {
        "type": "llm",
        "provider": "local",
        "model": "qwen3:4b-instruct-2507-fp16",
        "max_tags": 10,
        "min_tags": 5,
        "max_tokens": 8192,
        "prompt_mode": "compact",
        "context_lookback_pairs": 5,
        "context_bleed_threshold": 0.1,
        "keyword_fallback": {
            "tag_keywords": {
                "legal": ["court", "filing", "motion", "attorney", "judge", "case"],
                "medical": ["medication", "doctor", "lab", "symptom", "dose", "blood"],
                "code": ["function", "bug", "deploy", "git", "API", "database", "error"],
            },
            "tag_patterns": {
                "legal": [r"\b\d{2}-cv-\d+\b", r"\bN\.?J\.?S\.?A\.?\b"],
                "code": [r"\bdef \w+\(", r"\bclass \w+[:(]"],
            },
        },
    },
    "tag_rules": [
        {"match": "legal*", "priority": 9, "ttl_days": None},
        {"match": "medical*", "priority": 8, "ttl_days": 90},
        {"match": "debug*", "priority": 7, "ttl_days": 7},
        {"match": "*", "priority": 5, "ttl_days": 30},
    ],
    "compaction": {
        "soft_threshold": 0.70,
        "hard_threshold": 0.85,
        "protected_recent_turns": 6,
        "overflow_buffer": 1.2,
        "summary_ratio": 0.15,
        "min_summary_tokens": 200,
        "max_summary_tokens": 2000,
        "max_concurrent_summaries": 4,
        "llm_token_overhead": 2000,
    },
    "summarization": {
        "provider": "local",
        "model": "qwen3:4b-instruct-2507-fp16",
        "max_tokens": 1000,
        "temperature": 0.3,
    },
    "providers": {
        "local": {
            "type": "generic_openai",
            "base_url": "http://127.0.0.1:11434/v1",
        },
    },
    "storage": {
        "backend": "sqlite",
        "sqlite": {"path": ".virtualcontext/store.db"},
    },
    "facts": {
        "graph_links": True,
    },
    "tool_output": {
        "enabled": False,
    },
    "assembly": {
        "core_context_max_tokens": 18_000,
        "tag_context_max_tokens": 30_000,
        "facts_max_tokens": 20_000,
        "context_hint_enabled": True,
        "context_hint_max_tokens": 2000,
        "core_files": [],
    },
    "retrieval": {
        "skip_active_tags": True,
        "active_tag_lookback": 4,
        "inbound_tagger_type": "embedding",
        "embedding_model": "all-MiniLM-L6-v2",
        "embedding_threshold": 0.3,
        "strategy_config": {
            "default": {
                "min_overlap": 1,
                "max_results": 10,
                "max_budget_fraction": 0.25,
                "include_related": True,
            },
        },
    },
    "telemetry": {
        "enabled": True,
        "models_file": "models.yaml",
    },
}


AGENTIC_TEMPLATE = """\
# virtual-context configuration — agentic preset
# Generated by: virtual-context init agentic
# Docs: https://github.com/virtual-context/virtual-context
#
# Balanced defaults for autonomous agent conversations across any domain.
# Tags emerge from conversation — no predefined domains to configure.

version: "0.2"
storage_root: ".virtualcontext"
context_window: 120000
token_counter: "estimate"

paging:
  enabled: true
  auto_promote: true
  auto_evict: true
  max_tool_loops: 10

tag_generator:
  type: "llm"
  provider: "local"
  model: "qwen3:4b-instruct-2507-fp16"
  max_tags: 10
  min_tags: 5
  max_tokens: 8192
  prompt_mode: "compact"
  context_lookback_pairs: 5
  context_bleed_threshold: 0.1
  keyword_fallback:
    tag_keywords:
      legal: [court, filing, motion, attorney, judge, case]
      medical: [medication, doctor, lab, symptom, dose, blood]
      code: [function, bug, deploy, git, API, database, error]
    tag_patterns:
      legal:
        - "\\\\b\\\\d{2}-cv-\\\\d+\\\\b"
        - "\\\\bN\\\\.?J\\\\.?S\\\\.?A\\\\.?\\\\b"
      code:
        - "\\\\bdef \\\\w+\\\\("
        - "\\\\bclass \\\\w+[:(]"

tag_rules:
  - match: "legal*"
    priority: 9
    ttl_days: null
  - match: "medical*"
    priority: 8
    ttl_days: 90
  - match: "debug*"
    priority: 7
    ttl_days: 7
  - match: "*"
    priority: 5
    ttl_days: 30

compaction:
  soft_threshold: 0.70
  hard_threshold: 0.85
  protected_recent_turns: 6
  overflow_buffer: 1.2
  summary_ratio: 0.15
  min_summary_tokens: 200
  max_summary_tokens: 2000
  max_concurrent_summaries: 4
  llm_token_overhead: 2000

summarization:
  provider: "local"
  model: "qwen3:4b-instruct-2507-fp16"
  max_tokens: 1000
  temperature: 0.3

providers:
  local:
    type: "generic_openai"
    base_url: "http://127.0.0.1:11434/v1"

storage:
  backend: "sqlite"
  sqlite:
    path: ".virtualcontext/store.db"

facts:
  graph_links: true

assembly:
  core_context_max_tokens: 18000
  tag_context_max_tokens: 30000
  facts_max_tokens: 20000
  context_hint_enabled: true
  context_hint_max_tokens: 2000
  core_files: []

retrieval:
  skip_active_tags: true
  active_tag_lookback: 4
  inbound_tagger_type: "embedding"
  embedding_model: "all-MiniLM-L6-v2"
  embedding_threshold: 0.3
  strategy_config:
    default:
      min_overlap: 1
      max_results: 10
      max_budget_fraction: 0.25
      include_related: true

telemetry:
  enabled: true
  models_file: "models.yaml"
"""


agentic_preset = Preset(
    name="agentic",
    description="Agentic preset — balanced defaults for autonomous agent conversations "
                "across any domain, fact graph enabled",
    config_dict=AGENTIC_CONFIG,
    template=AGENTIC_TEMPLATE,
)

register_preset(agentic_preset)
