"""General-purpose preset — balanced defaults for mixed-domain conversations."""

from __future__ import annotations

from .base import Preset, register_preset


GENERAL_CONFIG: dict = {
    "version": "0.2",
    "storage_root": ".virtualcontext",
    "context_window": 120_000,
    "token_counter": "estimate",
    "tag_generator": {
        "type": "llm",
        "provider": "ollama",
        "model": "qwen3:4b-instruct-2507-fp16",
        "max_tags": 8,
        "min_tags": 2,
        "keyword_fallback": {
            "tag_keywords": {
                "general": ["project", "plan", "issue", "status", "priority"],
                "legal": ["court", "filing", "motion", "attorney", "judge"],
                "medical": ["medication", "doctor", "lab", "symptom", "dose"],
                "code": ["function", "bug", "deploy", "git", "api", "database"],
            },
            "tag_patterns": {
                "legal": [r"\b\d{2}-cv-\d+\b"],
                "code": [r"\bdef \w+\(", r"\bclass \w+[:(]"],
            },
        },
    },
    "tag_rules": [
        {"match": "legal*", "priority": 9, "ttl_days": None},
        {"match": "medical*", "priority": 8, "ttl_days": 90},
        {"match": "code*", "priority": 7, "ttl_days": None},
        {"match": "debug*", "priority": 7, "ttl_days": 14},
        {"match": "*", "priority": 5, "ttl_days": 30},
    ],
    "compaction": {
        "soft_threshold": 0.70,
        "hard_threshold": 0.85,
        "protected_recent_turns": 6,
        "overflow_buffer": 1.2,
        "summary_ratio": 0.15,
        "min_summary_tokens": 200,
        "max_summary_tokens": 2000,
        "max_concurrent_summaries": 4,
    },
    "summarization": {
        "provider": "ollama",
        "model": "qwen3:4b-instruct-2507-fp16",
        "max_tokens": 1000,
        "temperature": 0.3,
    },
    "providers": {
        "ollama": {
            "type": "generic_openai",
            "base_url": "http://127.0.0.1:11434/v1",
        },
    },
    "storage": {
        "backend": "sqlite",
        "sqlite": {"path": ".virtualcontext/store.db"},
        "filesystem": {"root": ".virtualcontext/store"},
    },
    "assembly": {
        "core_context_max_tokens": 18_000,
        "tag_context_max_tokens": 30_000,
        "core_files": [],
    },
    "retrieval": {
        "skip_active_tags": True,
        "active_tag_lookback": 4,
        "strategy_config": {
            "default": {
                "min_overlap": 1,
                "max_results": 10,
                "max_budget_fraction": 0.25,
                "include_related": True,
            },
        },
    },
    "cost_tracking": {
        "enabled": True,
        "pricing": {
            "ollama": {"input_per_1k": 0.0, "output_per_1k": 0.0},
        },
    },
}


GENERAL_TEMPLATE = """\
# virtual-context configuration — general preset
# Generated by: virtual-context init general
# Docs: https://github.com/virtual-context/virtual-context

version: "0.2"
storage_root: ".virtualcontext"
context_window: 120000
token_counter: "estimate"

tag_generator:
  type: "llm"
  provider: "ollama"
  model: "qwen3:4b-instruct-2507-fp16"
  max_tags: 8
  min_tags: 2
  keyword_fallback:
    tag_keywords:
      general: [project, plan, issue, status, priority]
      legal: [court, filing, motion, attorney, judge]
      medical: [medication, doctor, lab, symptom, dose]
      code: [function, bug, deploy, git, API, database]
    tag_patterns:
      legal:
        - "\\\\b\\\\d{2}-cv-\\\\d+\\\\b"
      code:
        - "\\\\bdef \\\\w+\\\\("
        - "\\\\bclass \\\\w+[:(]"

tag_rules:
  - match: "legal*"
    priority: 9
    ttl_days: null
  - match: "medical*"
    priority: 8
    ttl_days: 90
  - match: "code*"
    priority: 7
    ttl_days: null
  - match: "debug*"
    priority: 7
    ttl_days: 14
  - match: "*"
    priority: 5
    ttl_days: 30

compaction:
  soft_threshold: 0.70
  hard_threshold: 0.85
  protected_recent_turns: 6
  overflow_buffer: 1.2
  summary_ratio: 0.15
  min_summary_tokens: 200
  max_summary_tokens: 2000
  max_concurrent_summaries: 4

summarization:
  provider: "ollama"
  model: "qwen3:4b-instruct-2507-fp16"
  max_tokens: 1000
  temperature: 0.3

providers:
  ollama:
    type: "generic_openai"
    base_url: "http://127.0.0.1:11434/v1"

storage:
  backend: "sqlite"
  sqlite:
    path: ".virtualcontext/store.db"
  filesystem:
    root: ".virtualcontext/store"

assembly:
  core_context_max_tokens: 18000
  tag_context_max_tokens: 30000
  core_files: []

retrieval:
  skip_active_tags: true
  active_tag_lookback: 4
  strategy_config:
    default:
      min_overlap: 1
      max_results: 10
      max_budget_fraction: 0.25
      include_related: true

cost_tracking:
  enabled: true
  pricing:
    ollama:
      input_per_1k: 0.0
      output_per_1k: 0.0
"""


general_preset = Preset(
    name="general",
    description="General-purpose preset for mixed-domain conversations",
    config_dict=GENERAL_CONFIG,
    template=GENERAL_TEMPLATE,
)

register_preset(general_preset)

